{
  "openapi": "3.0.0",
  "info": {
    "title": "Sample API",
    "description": "Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.",
    "version": "0.1.9"
  },
  "servers": [
    {
      "url": "https://u6i8wt2u55.execute-api.us-east-1.amazonaws.com",
      "description": "Optional server description, e.g. Main (production) server"
    }
  ],
  "paths": {
    "/products": {
      "get": {
        "summary": "Returns a list of all products.",
        "description": "All products returned by the database",
        "responses": {
          "200": {
            "description": "A JSON array of product names",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "string"
                  }
                }
              }
            },
            "example": {
              "id": "df6b70e7-516f-4b45-9f19-3609227fda79",
              "position": 1,
              "name": "Calça",
              "grade": 4.5,
              "price": 57.67,
              "category": "Moda"
            }
          }
        }
      },
      "post": {
        "summary": "Create one product in database",
        "requestBody": {
          "description": "Optional description in *Markdown*",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestProduct"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "A JSON array of product names",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RequestProduct"
                },
                "example": {
                  "id": "df6b70e7-516f-4b45-9f19-3609227fda79",
                  "position": 1,
                  "name": "Calça",
                  "grade": 4.5,
                  "price": 57.67,
                  "category": "Moda"
                }
              }
            }
          }
        }
      }
    },
    "/products/:id": {
      "get": {
        "summary": "Returns a especific product of all products.",
        "parameters": [
          {
            "in": "path",
            "name": "productId",
            "type": "string",
            "required": true,
            "description": "Numeric ID of the product to get."
          }
        ],
        "description": "A product of database by product ID",
        "responses": {
          "200": {
            "description": "A JSON object with product info",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            },
            "example": [{
              "id": "df6b70e7-516f-4b45-9f19-3609227fda79",
              "position": 1,
              "name": "Calça",
              "grade": 4.5,
              "price": 57.67,
              "category": "Moda"
            },
            {
              "id": "ef6b77b5-516f-4b45-9f19-3609227dde65",
              "position": 2,
              "name": "Camisa",
              "grade": 4.7,
              "price": "R$ 57.67",
              "category": "Moda"
            }]
          }
        }
      },
      "delete": {
        "summary": "Deletes a especific product by the product ID.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "type": "string",
            "required": true,
            "description": "Numeric ID of the product to get."
          }
        ],
        "description": "A product of database by product ID",
        "responses": {
          "200": {
            "description": "A JSON object with deleted product info",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RequestProduct"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RequestProduct": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Product ID"
          },
          "name": {
            "type": "string",
            "description": "Product name"
          },
          "position": {
            "type": "number",
            "description": "Product position in the bestsellers ranking"
          },
          "grade": {
            "type": "number",
            "description": "Average rating of the product reviews"
          },
          "price": {
            "type": "string",
            "description": "Product price in R$ (Brazilian Real), hence it is a string"
          },
          "category": {
            "type": "string",
            "description": "Product category"
          }
        }        
      }
    }
  }
}